"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Footprints, LoaderCircle } from "lucide-react";
import { toast } from "react-toastify";
import { pollCoordinatedLook, startCoordinatedLook } from "@/lib/coordinated-look/coordinated-look.client";
import { readStyleFlow, updateStyleFlow, type StyleFlowState } from "@/lib/style-flow/style-flow.storage";
import { StyleFlowHeader } from "./style-flow-header";

export function ShoesFlowClient() {
  const router = useRouter(); const [flow, setFlow] = useState<StyleFlowState | null | undefined>(undefined); const [applying, setApplying] = useState(false); const [attempt, setAttempt] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => setFlow(readStyleFlow()), 0); return () => window.clearTimeout(timer); }, []);
  if (flow === undefined) return <div className="grid min-h-[60vh] place-items-center"><LoaderCircle className="animate-spin" /></div>;
  if (!flow) return <section className="grid min-h-[60vh] place-items-center"><button className="button-dark" onClick={() => router.replace("/dashboard")}>Create Beauty Palette</button></section>;
  const choose = (shoePresentation: "female" | "male") => { updateStyleFlow({ shoePresentation, shoesItemIndex: null }); setFlow({ ...flow, shoePresentation, shoesItemIndex: null }); };
  const applyShoes = async () => { if (!flow.bodyFileId || !flow.shoePresentation || !flow.shoesItemIndex || applying) return; const controller = new AbortController(); setApplying(true); setAttempt(0); try { const task = await startCoordinatedLook({ feature: "shoes", sourceFileId: flow.bodyFileId, gender: flow.shoePresentation, itemIndex: flow.shoesItemIndex }, controller.signal); const resultUrl = await pollCoordinatedLook("shoes", task, controller.signal, setAttempt); updateStyleFlow({ shoesResultUrl: resultUrl }); setFlow({ ...flow, shoesResultUrl: resultUrl }); } catch (error) { toast.error(error instanceof Error ? error.message : "Shoes try-on failed."); } finally { setApplying(false); } };
  return <section><StyleFlowHeader step="05" title="Ground the look" description="Choose a presentation and one of ten shoe references for the final try-on." /><div className="grid gap-6 lg:grid-cols-[minmax(17rem,0.8fr)_minmax(0,1.2fr)]"><div className="mx-auto w-full max-w-[24rem]"><div className="aspect-[4/5] rounded-[8px] bg-[var(--surface-container-high)] bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${JSON.stringify(flow.shoesResultUrl ?? flow.clothingResultUrl ?? flow.bodyDataUrl ?? flow.portraitDataUrl).slice(1, -1)})` }} /></div><div><p className="eyebrow"><Footprints size={13} /> Shoe presentation</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{([['female','Feminine styling'],['male','Masculine styling']] as const).map(([value,label]) => <button key={value} onClick={() => choose(value)} className={`relative rounded-[8px] border p-4 text-left text-sm ${flow.shoePresentation === value ? "border-[var(--burgundy)] bg-[var(--surface-container-low)]" : "border-[var(--line)]"}`}>{label}{flow.shoePresentation === value && <Check size={14} className="absolute right-3 top-3" />}</button>)}</div>{flow.shoePresentation && <div className="mt-4 grid grid-cols-5 gap-2">{Array.from({ length: 10 }, (_, index) => index + (flow.shoePresentation === "male" ? 11 : 1)).map((itemIndex) => <button type="button" key={itemIndex} onClick={() => { updateStyleFlow({ shoesItemIndex: itemIndex }); setFlow({ ...flow, shoesItemIndex: itemIndex }); }} className={`aspect-square rounded-[6px] border bg-contain bg-center bg-no-repeat ${flow.shoesItemIndex === itemIndex ? "border-[var(--burgundy)]" : "border-[var(--line)]"}`} style={{ backgroundImage: `url(/catalog/shoes-${String(itemIndex).padStart(2, "0")}.jpg)` }} />)}</div>}<button type="button" onClick={() => void applyShoes()} disabled={!flow.shoePresentation || !flow.shoesItemIndex || !flow.bodyFileId || applying} className="button-dark mt-6 disabled:opacity-40">{applying ? <LoaderCircle size={14} className="animate-spin" /> : <Footprints size={14} />}{applying ? `Applying · ${attempt}` : "Try shoes"}</button></div></div>{flow.shoesResultUrl && <div className="mt-6 flex justify-end border-t border-[var(--line)] pt-5"><button type="button" onClick={() => router.push("/look")} className="button-dark">View final look <ArrowRight size={14} /></button></div>}</section>;
}
